import pdfMake from 'pdfmake';
const fonts = {
  Roboto: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

const printer = new pdfMake(fonts);

function generateBillPDF(billData) {
  const {
    items,
    vatPercent = 13,
    discountPercent = 0,
    totalPaid = 0,
    username,
    panNo,
    regNo
  } = billData;

  // Calculate line totals
  const tableBody = [
    [{ text: 'S.N.', style: 'tableHeader' }, { text: 'Particulars', style: 'tableHeader' }, { text: 'Qty', style: 'tableHeader' }, { text: 'Rate', style: 'tableHeader' }, { text: 'Amount', style: 'tableHeader' }]
  ];

  let subtotal = 0;
  items.forEach((item, index) => {
    const amount = item.quantity * item.rate;
    subtotal += amount;
    tableBody.push([
      index + 1,
      item.name,
      item.quantity,
      item.rate.toFixed(2),
      amount.toFixed(2)
    ]);
  });

  const vatAmount = (subtotal * vatPercent) / 100;
  const totalBeforeDiscount = subtotal + vatAmount;
  const discountAmount = (totalBeforeDiscount * discountPercent) / 100;
  const finalTotal = totalBeforeDiscount - discountAmount;
  const change = totalPaid - finalTotal;

  const now = new Date();
  const formattedDate = now.toLocaleString('en-IN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });

  const docDefinition = {
    content: [
      { text: 'RestroX', style: 'header' },
      { text: `PAN No.: ${panNo} | Reg. No.: ${regNo}`, style: 'subheader' },
      '\n',
      {
        table: {
          headerRows: 1,
          widths: ['auto', '*', 'auto', 'auto', 'auto'],
          body: tableBody
        },
        layout: 'lightHorizontalLines'
      },
      '\n',
      {
        columns: [
          { width: '*', text: '' },
          {
            width: 'auto',
            stack: [
              { text: `Subtotal: Rs. ${subtotal.toFixed(2)}`, style: 'totalLine' },
              { text: `VAT (${vatPercent}%): Rs. ${vatAmount.toFixed(2)}`, style: 'totalLine' },
              { text: `Discount (${discountPercent}%): -Rs. ${discountAmount.toFixed(2)}`, style: 'totalLine' },
              { text: `Total: Rs. ${finalTotal.toFixed(2)}`, style: 'totalLineBold' },
              { text: `Paid: Rs. ${totalPaid.toFixed(2)}`, style: 'totalLine' },
              { text: `Change: Rs. ${change >= 0 ? change.toFixed(2) : '0.00'}`, style: 'totalLine' }
            ]
          }
        ]
      },
      '\n\n',
      { text: `Generated by: ${username}`, style: 'footer' },
      { text: `Date & Time: ${formattedDate}`, style: 'footer' }
    ],
    styles: {
      header: {
        fontSize: 22,
        bold: true,
        alignment: 'center',
        margin: [0, 0, 0, 10]
      },
      subheader: {
        fontSize: 10,
        alignment: 'center',
        margin: [0, 0, 0, 15]
      },
      tableHeader: {
        bold: true,
        fontSize: 10,
        alignment: 'center'
      },
      totalLine: {
        fontSize: 10,
        alignment: 'right'
      },
      totalLineBold: {
        fontSize: 11,
        bold: true,
        alignment: 'right'
      },
      footer: {
        fontSize: 9,
        alignment: 'left',
        margin: [0, 10, 0, 0]
      }
    },
    defaultStyle: {
      fontSize: 10
    }
  };

  const pdfDoc = printer.createPdfKitDocument(docDefinition);
  return pdfDoc;
}

export default generateBillPDF;